/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package padraoprojeto.Iterator.interfacegrafica;

import padraoprojeto.Iterator.classeDados.Piloto;
import padraoprojeto.Iterator.persistencia.PilotoPersistencia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Iterator;
import padraoprojeto.Iterator.classeDados.Piloto;


/**
 *
 * @author eugeniojulio
 */
public class JanelaApresentacao extends javax.swing.JFrame {

    /**
     * Creates new form JanelaApresentacao
     */
    public JanelaApresentacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonListarLinkedList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDados = new javax.swing.JTable();
        jButtonListarHashSet = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonListarTreeSet = new javax.swing.JButton();
        jButtonListarHashMap = new javax.swing.JButton();
        jButtonListarStack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonListarLinkedList.setText("LinkedList");
        jButtonListarLinkedList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarLinkedListActionPerformed(evt);
            }
        });

        jTableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Pais", "Idade", "Equipe", "Motor", "Pontos"
            }
        ));
        jScrollPane1.setViewportView(jTableDados);

        jButtonListarHashSet.setText("HashSet");
        jButtonListarHashSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarHashSetActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonListarTreeSet.setText("TreeSet");
        jButtonListarTreeSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarTreeSetActionPerformed(evt);
            }
        });

        jButtonListarHashMap.setText("HashMap");
        jButtonListarHashMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarHashMapActionPerformed(evt);
            }
        });

        jButtonListarStack.setText("Stack");
        jButtonListarStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarStackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButtonListarLinkedList)
                .addGap(18, 18, 18)
                .addComponent(jButtonListarHashSet)
                .addGap(18, 18, 18)
                .addComponent(jButtonListarTreeSet)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpar)
                .addGap(30, 30, 30)
                .addComponent(jButtonListarHashMap)
                .addGap(18, 18, 18)
                .addComponent(jButtonListarStack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarLinkedList)
                    .addComponent(jButtonListarHashSet)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonListarTreeSet)
                    .addComponent(jButtonListarHashMap)
                    .addComponent(jButtonListarStack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void imprimirDadosNaGrid(Iterator conjunto){
    DefaultTableModel model = (DefaultTableModel) jTableDados.getModel();
    model.setNumRows(0);

    while (conjunto.hasNext()) {
        Piloto p = (Piloto) conjunto.next();
        String[] linha = new String[7];
        linha[0] = String.valueOf(p.getCodigo());
        linha[1] = p.getNome();
        linha[2] = p.getPais();
        linha[3] = String.valueOf(p.getIdade());
        linha[4] = p.getEquipe();
        linha[5] = p.getMotor();
        linha[6] = String.valueOf(p.getPontos());
        model.addRow(linha);
    }
}
    private void jButtonListarLinkedListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarLinkedListActionPerformed
        // TODO add your handling code here:
    try {
        PilotoPersistencia dados = new PilotoPersistencia("./src/padraoprojeto/Iterator/dados/DadosDosPilotosF1.csv");
        imprimirDadosNaGrid(dados.listarComLinkedList());
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(rootPane, erro);
    }
    }//GEN-LAST:event_jButtonListarLinkedListActionPerformed

    private void jButtonListarHashSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarHashSetActionPerformed
        // TODO add your handling code here:
    try {
        PilotoPersistencia dados = new PilotoPersistencia("./src/padraoprojeto/Iterator/dados/DadosDosPilotosF1.csv");
        imprimirDadosNaGrid(dados.listarComHashSet());
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(rootPane, erro);
    }     
    }//GEN-LAST:event_jButtonListarHashSetActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =  (DefaultTableModel) jTableDados.getModel();
        model.setNumRows(0);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonListarTreeSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarTreeSetActionPerformed
        // TODO add your handling code here:
    try {
        PilotoPersistencia dados = new PilotoPersistencia("./src/padraoprojeto/Iterator/dados/DadosDosPilotosF1.csv");
        imprimirDadosNaGrid(dados.listarComTreeSet());
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(rootPane, erro);
    }
    }//GEN-LAST:event_jButtonListarTreeSetActionPerformed

    private void jButtonListarHashMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarHashMapActionPerformed
    try {
    PilotoPersistencia dados = new PilotoPersistencia("./src/padraoprojeto/Iterator/dados/DadosDosPilotosF1.csv");
    imprimirDadosNaGrid(dados.listarComHashMap());
} catch (Exception erro) {
    JOptionPane.showMessageDialog(rootPane, erro);
}
    }//GEN-LAST:event_jButtonListarHashMapActionPerformed

    private void jButtonListarStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarStackActionPerformed
    try {
        PilotoPersistencia dados = new PilotoPersistencia("./src/padraoprojeto/Iterator/dados/DadosDosPilotosF1.csv");
        imprimirDadosNaGrid(dados.listarComStack());
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(rootPane, erro);
    }
    }//GEN-LAST:event_jButtonListarStackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaApresentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonListarHashMap;
    private javax.swing.JButton jButtonListarHashSet;
    private javax.swing.JButton jButtonListarLinkedList;
    private javax.swing.JButton jButtonListarStack;
    private javax.swing.JButton jButtonListarTreeSet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDados;
    // End of variables declaration//GEN-END:variables
}
